repos:
  github-configuration-nike-auto: disabled
  github-configuration-.*:
    codeowners:
      '*.py': '@dvere'
    settings:
      description: REPO DESCRIPTION
      private: true
    autolink:
      - key_prefix: 'PROJECT-'
        url_template: 'https://jira.nike.com/browse/PROJECT-<num>'
      - key_prefix: 'TEST-'
        url_template: 'https://jira.nike.com/browse/TEST-<num>'
    collaborators:
      - username: asafo1_nike
        permission: admin
      - username: svarak_nike
        permission: admin
      - username: dverv2_nike
        permission: admin
    webhooks:
      - events:
          - pull_request
          - repository
          - push
        active: false
        config:
          url: 'https://smee.io/h0ob8MKTFSwMsdB'
          content_type: 'json'
          secret: null
          insecure_ssl: 0
          toke: null
          digest: null
  github-configuration-nike.*: {}
