name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: echo github
        run: |
          cat << OBJECT
          ${{ toJson(github) }}
          OBJECT
      - name: echo secrets
        run: |
          cat << OBJECT
          ${{ toJson(secrets) }}
          OBJECT
