name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actios:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{secrets.SECRET_TOKEN}}
