name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actios:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.SECRET_TOKEN }}
      - name: echo github
        run: |
          cat << OBJECT
          ${{ toJson(github) }}
          OBJECT
      - name: echo secrets
        run: |
          cat << OBJECT
          ${{ toJson(secrets) }}
          OBJECT
      - name: Workflow Webhook Action
        uses: distributhor/workflow-webhook@v2.0.2
        env:
          webhook_url: "https://smee.io/giZgfuYtb0hOXfxe"
          webhook_secret: "qwerty123"
          webhook_type: "json"
          data: '{ "repository": "${{github.event.repository.full_name}}", "number": "${{github.event.number}}", "created_at": "${{github.event.pull_request.created_at}}", "updated_at": "${{github.event.pull_request.updated_at}}" }'

      
